env:
  browser: true
extends:
  - "eslint:recommended"
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: latest
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  no-unused-vars:
    - off
  "@typescript-eslint/no-unused-vars":
    - error
