name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout dist
        uses: actions/checkout@v2
        with:
          refs: ph-pages
          path: dist
      - name: Build
        run: npm run build
      - name: Commit
        working-directory: dist
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@example.com"
          git add .
          git commit -m "Built from commit $(cd .. && git log -n 1 --format=%h)"
      - name: Push
        working-directory: dist
        run: git push
